name: Go

on:
    push:
      tags:
        - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Init GoLang
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -v ./...

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: fh_sms_notice
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}